Repository Sv443/JokeAPI, pull requests merged in 2021-12, with the labels that each got.

#365 Reflag some jokes
  data/jokes/regular/jokes-en.json
Labels: joke edit

#367 update dependent link
  README.md
  docs/raw/index.html
Labels: dependent

#366 Update errorMessages.js
  data/errorMessages.js
Labels: enhancement
